"""Remove parties table and party_id from line_items

Revision ID: 33c2fccb211e
Revises: e8f383ab67fa
Create Date: 2025-10-30 21:03:01.587792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33c2fccb211e'
down_revision: Union[str, Sequence[str], None] = 'e8f383ab67fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint first
    op.drop_constraint('line_items_party_id_fkey', 'line_items', type_='foreignkey')
    op.drop_column('line_items', 'party_id')
    # Now drop the parties table
    op.drop_table('parties')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_items', sa.Column('party_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('line_items_party_id_fkey'), 'line_items', 'parties', ['party_id'], ['id'], ondelete='SET NULL')
    op.create_table('parties',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_ignored', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('parties_pkey')),
    sa.UniqueConstraint('name', name=op.f('parties_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
