"""add event_id to notifications

Revision ID: 954cd78cdba6
Revises: 8cf1447285c6
Create Date: 2026-04-08 17:57:25.893418

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "954cd78cdba6"
down_revision: Union[str, Sequence[str], None] = "8cf1447285c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("event_id", sa.String(length=255), nullable=True))
    op.create_foreign_key("fk_notifications_event_id", "notifications", "events", ["event_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_notifications_event_id", "notifications", type_="foreignkey")
    op.drop_column("notifications", "event_id")
    # ### end Alembic commands ###
