"""Add responsible_party column to line_items

Revision ID: c967c3314f9f
Revises: 261fbe964e53
Create Date: 2025-11-01 13:27:08.794364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c967c3314f9f'
down_revision: Union[str, Sequence[str], None] = '261fbe964e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_items', sa.Column('responsible_party', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_items', 'responsible_party')
    # ### end Alembic commands ###
