"""Add currency and balance fields to bank_accounts

Revision ID: fb7a20ffd5fe
Revises: 89d79c1aa775
Create Date: 2025-11-20 17:51:57.472713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7a20ffd5fe'
down_revision: Union[str, Sequence[str], None] = '89d79c1aa775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('bank_accounts', sa.Column('latest_balance', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('bank_accounts', sa.Column('balance_as_of', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'balance_as_of')
    op.drop_column('bank_accounts', 'latest_balance')
    op.drop_column('bank_accounts', 'currency')
    # ### end Alembic commands ###
