# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Client CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # Testing against Node 16.x (lts/gallium) which is typically used for this project
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    
    - name: Debug - Check working directory and files
      run: |
        pwd
        ls -la
        echo "Checking client directory:"
        ls -la client/
        echo "Checking package-lock.json:"
        head -5 client/package-lock.json
    
    - name: Install dependencies
      working-directory: client
      run: npm ci --legacy-peer-deps
    
    #   TODO: Consider upgrading to react-scripts version 5.x instead of downgrading @testing-library/jest-dom
    - name: Downgrade @testing-library/jest-dom for compatibility
      working-directory: client
      run: npm install @testing-library/jest-dom@5.16.5 --legacy-peer-deps
    
    - name: Build the application
      working-directory: client
      run: npm run build
    
    - name: Run tests
      working-directory: client
      run: npm test 